Improved: Update build.gradle to the latest dependencies
(OFBIZ-11603)

Reverts to shiro-core:1.4.1, got this issue in loadAll:

Exception in thread "main" org.apache.shiro.crypto.CryptoException:
Unable to execute 'doFinal' with cipher instance [javax.crypto.Cipher@44a98a23].
[...]
at org.apache.ofbiz.entity.datasource.GenericDAO.insert(GenericDAO.java:110)
[...]
Caused by:
javax.crypto.IllegalBlockSizeException: Input length not multiple of 16 bytes
at com.sun.crypto.provider.CipherCore.finalNoPadding(CipherCore.java:1109)
at com.sun.crypto.provider.CipherCore.fillOutputBuffer(CipherCore.java:1053)
at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:853)
at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:446)
at javax.crypto.Cipher.doFinal(Cipher.java:2164)
at org.apache.shiro.crypto.JcaCipherService.crypt(JcaCipherService.java:459)