Improved: avoids error message related to call to getUiLabels w/o parameters
I discovered this by chance while looking for the behaviour of Freemarker <#sep>
tag.

Error running script at location [...GetUiLabels.groovy]:
java.lang.IllegalArgumentException: Text must not be null or empty
  at groovy.json.JsonSlurper.parseText(JsonSlurper.java:203)
  at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
  at org.apache.ofbiz.common.GetUiLabels.run(GetUiLabels.groovy:21) ~[main/:?]

I guess this should not happen because calls to getUiLabels w/o parameters
should not happen. Anyway, prevents that in case (no Jira, no backport)